CREATE TABLE [dbo].[ORDEN_DETALLE] (
    [ORDEN_FK_ORDEN_DETALLE]    UNIQUEIDENTIFIER NOT NULL,
    [PRODUCTO_FK_ORDEN_DETALLE] UNIQUEIDENTIFIER NOT NULL,
    [Cantidad]                  INT              NOT NULL,
    [Precio_Unitario]           DECIMAL (18, 2)  NOT NULL,
    [Subtotal]                  DECIMAL (18, 2)  NOT NULL,
    CONSTRAINT [ORDEN_DETALLE_PK_CK] PRIMARY KEY CLUSTERED ([ORDEN_FK_ORDEN_DETALLE] ASC, [PRODUCTO_FK_ORDEN_DETALLE] ASC),
    CONSTRAINT [ORDEN_ORDEN_FK_CK] FOREIGN KEY ([ORDEN_FK_ORDEN_DETALLE]) REFERENCES [dbo].[ORDEN] ([ORDEN_PK]),
    CONSTRAINT [PRODUCTO_PRODUCTO_FK_CK] FOREIGN KEY ([PRODUCTO_FK_ORDEN_DETALLE]) REFERENCES [dbo].[PRODUCTO] ([PRODUCTO_PK])
);

