CREATE TABLE [dbo].[ORDEN] (
    [ORDEN_PK] UNIQUEIDENTIFIER NOT NULL,
    [Fecha]    DATETIME         NOT NULL,
    [Total]    DECIMAL (18, 2)  NOT NULL,
    CONSTRAINT [ORDEN_ORDEN_PK_CK] PRIMARY KEY CLUSTERED ([ORDEN_PK] ASC)
);

